### ISSUE TITLE
Azure Cloud Foundry Servers

### ISSUE THREAD

**Issue by kennetham** [Azure/bosh#2]
Hi team, I understand that Cloud Foundry deployment of cf-release will create multiple instances on Azure. Am I able to do that on one server instead?

Does Azure have examples on running Openstack as well on Linux flavors?

I have checked out Cloud foundry example by @NingKuang and I was wondering how can I compact the deployments to one VM or 2 instead of an array of VMs.

**Comment by AbelHu** [comment]
1. You can deploy CF on one server. We have a sample yaml file for you. And current preview code only works on one server. https://github.com/Azure/bosh/blob/azure_cpi_crp/deploy_for_azure/config/micro_cf.yml
2. You can use Azure as the infrastructure to deploy cloud foundry now.

**Comment by kennetham** [comment]
@AbelHu Great, so correct me if I am wrong. I have already provisioned the Cloud Foundry template, so I would need to follow this `micro_cf.yml` and it will deploy cloud foundry on my instance, and I can use Standard_A2 not an issue right?

Furthermore, I noticed resource pool etc are using Large_z1, what does this incur for me?

How do I identify the cf login api to use and push an app right after it is deployed? Any examples or guide through?

**Comment by AbelHu** [comment]
You can follow https://github.com/Azure/bosh/blob/azure_cpi_crp/deploy_for_azure/guide_template.doc to deploy CF.
You also need to prepare a DNS server if you want to use the domain name cf.azurelovecf.com in the sample file micro_cf.yml

You can use any Azure VM size if you want.

pool is used to create VMs for CF package compilation. After packages are compiled, these VMs will be deleted automatically.

For cloud foundry usage, you can get docs and examples from cloud foundry site. http://docs.cloudfoundry.org/

**Comment by kennetham** [comment]
@AbelHu I got you. I will try it out and see. One last question, DNS server has to be pointed to Azure instance or I can use my Azure instance as the domain as such, cfexample.cloudapp.net?

I would have to replace `cf.azurelovecf.com` with my desired domain name correct?

I don't have to edit anything else besides the domain in micro_cf.yml by the way right?

**Comment by AbelHu** [comment]
Yes, you can use Azure domain. The VMs which are created by BOSH are new Azure compute node. You should use the domain such as VMNAME.LOCATION.cloudapp.azure.com.

You also need to update other items by following the guide if you use the example micro_cf.yml.

director_uuid => Use above Director.UUID
jobs.name[cf_z1].networks.name[reserved].static_ips => Public IP for cloud foundry. “cf-ip” in your home folder ~/settings
jobs.name[cf_z1].Properties.ha_proxy.ssl_pem => The content of your SSL certificate for HAProxy

**Comment by kennetham** [comment]
Hi @AbelHu, What I don't understand is the DNS domain. Once BOSH deploys the cloud foundry, it is as VMNAME.LOCATION.cloudapp.azure.com instead of VMNAME.cloudapp.net?

So if I were to deploy buildpack-1 in Java for instance, I would have to cf login to api.VMNAME.LOCATION.cloudapp.azure.com? That should return me a javaapp.VMNAME.LOCATION.cloudapp.azure.com? Subsequently if I were to deploy buildpack-2 in Ruby, rubyapp.VMNAME.LOCATION.cloudapp.azure.com?

That is to say, if I have my own domain say cfapp.com -> bind DNS CNAME record to Compute node and it should replace VMNAME.LOCATION.cloudapp.azure.com with cfapp.com. Is this right?

Could I ping you privately if I have further questions?

**Comment by AbelHu** [comment]
BOSH creates Azure V2 VMs for Cloud Foundry. 
Azure V2 VMs use VMNAME.LOCATION.cloudapp.azure.com as domain name. Azure V1 VMs use CLOUDSERVICE.cloudapp.net. You can reference https://azure.microsoft.com/en-in/documentation/articles/virtual-machines-azurerm-versus-azuresm/.

If you use your own domain, you can bind the public IP of CF VM to your domain and then use it.

If you have questions about cloud foundry, I suggest you can get help from this forum. https://groups.google.com/a/cloudfoundry.org/forum/#!forum/vcap-dev

**Comment by kennetham** [comment]
I think I would have more questions with how Cloud Foundry is deployed within Azure than Cloud Foundry itself. But sounds good, in fact the community list died down for quite awhile, I have been trying to hit the list but haven't gotten much replies, so just got off another issue tracker with Cloud Foundry dev team, the best I could get is through git issues for now.

Great! I will give it a go and see how that works.

**Comment by AbelHu** [comment]
If you have questions about CF on Azure, welcome you to discuss them here. If the questions are not related with Azure, the community forum is the better place.

You can see the price of Azure VMs in this link http://azure.microsoft.com/en-in/pricing/details/virtual-machines/#Linux. There is no difference for the VMs which are created by BOSH.

**Comment by kennetham** [comment]
Great! I got you! Thank you for the advise!

**Comment by kennetham** [comment]
@AbelHu When the template has been successfully deployed, can I say that MicroBosh has also been uploaded and I do not need to deploy MicroBosh again. My next course of action would be to deploy a single VM of cloud foundry within this template VM instance. AM I right to say that?

Do I need HAProxy and SSL or I could do without it?

Thank you.

**Comment by AbelHu** [comment]
You can read the Guide https://github.com/Azure/bosh/blob/azure_cpi_crp/deploy_for_azure/guide_template.doc.

**Comment by kennetham** [comment]
I followed the document, but I have trouble with the Azure Xplat CLI. I can't seem to login.
I am getting this error.

```text
+ Authenticating...                                                            
error:   Server returned an unknown AccountType: undefined
info:    Error information has been recorded to /Users/kennetham/.azure/azure.err
error:   login command failed
```

So when I connect to this VM instance, there is no BOSH director, which means I have to first deploy MicroBOSH to 1 VM instance, then secondly, I need to deploy micro_cf.yml? I have been gathering all the resources including the documents but I still do not understand how this works in Azure.

I hope you can explain, I am trying to run this so I could do a demo.

**Comment by AbelHu** [comment]
You should assure you have a valid Microsoft account and Azure subscription. You should see the log details in /Users/kennetham/.azure/azure.err.

The template only helps you to deploy a dev box. You can login to the dev box and then deploy a MicroBosh easily. After you deploy MicroBosh, you can reference micro_cf.yml to deploy cloud foundry on Azure.

**Comment by kennetham** [comment]
@AbelHu Yup I do have a valid Microsoft account and Azure subscription that is running.

Ah I see, in the dev box, I supposed MicroBosh and Cloud Foundry are deployed in the same dev box?

**Comment by AbelHu** [comment]
You can use bosh on the dev box to deploy MicroBosh and Cloud Foundry.
Suggest you read the docs in http://bosh.io/docs before you deploy.

**Comment by kennetham** [comment]
Yup I have been deploying Cloud Foundry on bare metal servers as well as to OpenStack, but with regards to Azure, I am not sure how different it is since now I am working on a template that pretty much sets up most of the process.

The issue now that I am facing is I am unable to connect to Azure ARM and login, and therefore unable to get the tenant_id, etc.

Please advise.

Thanks

**Comment by AbelHu** [comment]
You can reference below doc:
https://azure.microsoft.com/en-in/documentation/articles/virtual-machines-command-line-tools/
https://azure.microsoft.com/en-in/documentation/articles/xplat-cli/

If you still have issues, you can ask in this branch. 
https://github.com/Azure/azure-xplat-cli

**Comment by kennetham** [comment]
Alright cool thanks!
