### ISSUE TITLE
Lost on deployment..

### ISSUE THREAD

**Issue by libby2cm** [Azure/bosh#4]
Been trying to deploy azurebosh via the arm template, per the guide that is floating around, but apparently something has changed and it does not work the same.  After deploying the template, it appears to be doing a regular bosh deployment vs using microbosh.  After the rg is deployed, I install npm, azure cli, etc., & setup the SPN & such.  I then update the ~/bosh.yml file to reflect subscription ID, app id, etc., then kick off the deploy_bosh.sh installer, which appears to succeed, but then because the guide directions are skewed, I don't know where the stemcell is that is to be uploaded.

Is the project in a state of flux now or something?  Should I use the manual process?

**Comment by AbelHu** [comment]
Sorry for the trouble. We release a new version. It will be announced officially very soon.
You can reference the new guide [here](https://github.com/Azure/bosh-azure-cpi-release/blob/master/docs/template-guide.md)

**Comment by libby2cm** [comment]
Thanks, @AbelHu !  I just found that out from another reply on the template repo.. I figured there was something simple I had missed!
